# Generated by Django 3.2.16 on 2023-03-10 11:00

import course_discovery.apps.course_metadata.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_first_name'),
        ('course_metadata', '0305_auto_20221125_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSubscription',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('subscription_eligible', models.BooleanField(default=False)),
                ('program_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='course_metadata.program')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(course_discovery.apps.course_metadata.models.PkSearchableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProgramSubscriptionPrice',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.OneToOneField(default='USD', on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
                ('program_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='course_metadata.programsubscription')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
